name: Deploy static content to Pages with Cypress tests

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job de testes e deploy
  cypress-tests-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configurar o Node.js (para instalar dependências)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.14.0'

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          npm install

      # Passo 4: Rodar os testes do Cypress
      - name: Run Cypress tests
        run: |
          npx cypress run --headless

      # Passo 5: Configurar Pages (se tudo passar)
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Passo 6: Fazer upload do artefato para o GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' 

      # Passo 7: Fazer o deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
