name: Run Cypress tests and Deploy to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "cypress-tests"
  cancel-in-progress: false

jobs:
  cypress-tests-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout code
        uses: actions/checkout@v4

      # Passo 2: Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Usando uma versão estável do Node.js (18.x ou 16.x)

      # Passo 3: Instalar dependências
      - name: Install dependencies
        run: |
          npm install

      # Passo 4: Rodar os testes do Cypress
      - name: Run Cypress tests
        run: |
          npx cypress run --headless

      # Passo 5: Configurar Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Passo 6: Fazer upload dos arquivos necessários para o GitHub Pages
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './site'  # Aqui você envia o diretório que contém seus arquivos estáticos (HTML, CSS, JS)

      # Passo 7: Fazer deploy para o GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
